server:
  port: 5002
spring:
  application:
    name: airline-core-service
  datasource:
    url: jdbc:mysql://localhost:3307/airline_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
